/*
 * RightClickContext.java
 *
 * Created on 22 March 2008, 20:43
 */

package com.github.cornerco.movieviewer;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author  Peter Hoek
 */
public class RightClickContext extends javax.swing.JDialog {
    
    MovieEntry entry = null;
    /** Creates new form RightClickContext */
    public RightClickContext(java.awt.Frame parent, boolean modal, MovieEntry me) {
        super(parent, modal);
        initComponents();
        this.setTitle(me.getTitle());
        this.entry = me;
        jTextField1.setText(""+me.getViewings());
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        //this.setVisible(true);
    }
    
    public void setCheck(boolean b)
    {
        jCheckBox1.setSelected(b);
        
    }
    

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setText("Lock");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Counter:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Reset Counter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setText("0");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox1)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        MovieViewer mv = (MovieViewer)(this.getParent());
        JCheckBox jcb = (JCheckBox) evt.getSource();
        if(jcb.isSelected())
            mv.addFileToProtected();
        else
            mv.removeFileFromProtected();
       
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MovieViewer m = (MovieViewer)(this.getParent());
        File f = entry.getFile();
        m.setViewCounter(f.getAbsolutePath(),0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if(evt.getKeyChar()==evt.VK_ENTER)
        {
            MovieViewer m = (MovieViewer)(this.getParent());
            File f = entry.getFile();
            int i = Integer.parseInt(jTextField1.getText());
            m.setViewCounter(f.getAbsolutePath(),i);  
        } 
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //System.out.println(entry.toString());
        File f = entry.getFile();
        String fname = f.toString();
        fname = fname.toLowerCase();

        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " +entry.toString(), "Delete?",  JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
            int reply2 = JOptionPane.showConfirmDialog(null, "Are you sure you REALLY SURE" , "Delete?",  JOptionPane.YES_NO_OPTION);
            if (reply2 == JOptionPane.YES_OPTION){
            
                if (!fname.endsWith("ifo"))
                    f.delete();

                else
                {
                    //yeah don't do this...if a ifo is in the root directory everything will be wiped out
                    //VERY DANGEROUS STOP STOP
                        File Dir = f.getParentFile();
                        //for(File f2: Dir.listFiles()) f2.delete();
                        //Dir.delete();
                    f.delete();//delete the ifo and delete the rest by hand
                    File f3 = new File(Dir+"\\DELETE EVERYTHING.GO");
                    try {
                        Writer output = new BufferedWriter(new FileWriter(f3));
                        output.close();
                    } catch (IOException ex) {
                        Logger.getLogger(RightClickContext.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        
        MovieViewer mv = (MovieViewer) this.getParent();
        mv.refreshFileList(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RightClickContext dialog = new RightClickContext(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
