/*
 * SelectFolder.java
 *
 * Created on 16 March 2008, 10:33
 */

package com.github.cornerco.movieviewer;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author  Peter Hoek
 */
public class SelectFile extends javax.swing.JFrame {
    
    MovieViewer me=null;
    /** Creates new form SelectFolder */
    public SelectFile(MovieViewer me) {
        this.me = me;
        initComponents();
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jFileChooser1.setBackground(new java.awt.Color(204, 255, 204));
        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jFileChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFileChooser1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFileChooser1KeyPressed
      
    }//GEN-LAST:event_jFileChooser1KeyPressed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
         //System.out.println(evt.getActionCommand());
         
         if(evt.getActionCommand().equals("ApproveSelection"))
         {
             JFileChooser j = (JFileChooser)evt.getSource();
             File f = j.getSelectedFile();
             me.setVeiwerProgram(f);
         }
         
         //this.setVisible(false);
         this.dispose();
       

        
    }//GEN-LAST:event_jFileChooser1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectFolder().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
    
}
